#ifndef _TEXTURE_H_
#define _TEXTURE_H_

//InitTexture
void InitTexture1(void);
void InitTexture2(void);
void InitTexture3(void);
void InitTexture4(void);
void InitTexture5(void);
void InitTexture6(void);
void InitTexture7(void);
void InitTexture8(void);
void InitTexture9(void);
void InitTexture10(void); 
void InitTexture11(void);
void InitTexture12(void);
void InitTexture13(void);
void InitTexture14(void); 
void InitTexture15(void);
void InitTexture16(void);
void InitTexture17(void);
void InitTexture18(void);
void InitTexture19(void);
void InitTexture20(void);
void InitTexture21(void);
void InitTexture22(void);
void InitTexture23(void);
void InitTexture24(void);
void InitTexture25(void);
void InitTexture26(void);
void InitTexture27(void);
void InitTexture28(void);
void InitTexture29(void);
void InitTexture30(void);
void InitTexture31(void);
void InitTexture32(void);
void InitTexture33(void);
void InitTexture34(void);
void InitTexture35(void);
void InitTexture36(void);
void InitTexture37(void);
void InitTexture38(void);
void InitTexture39(void);
void InitTexture40(void);
void InitTexture41(void);
void InitTexture42(void);
void InitTexture43(void);
void InitTexture44(void);
void InitTexture45(void);
void InitTexture46(void);
void InitTexture47(void);
void InitTexture48(void);
void InitTexture49(void);
void InitTexture50(void);
void InitTexture51(void);
void InitTexture52(void);
void InitTexture53(void);
void InitTexture54(void);
void InitTexture55(void);
void InitTexture56(void);
void InitTexture57(void);
void InitTexture58(void);
void InitTexture59(void);
void InitTexture60(void);
void InitTexture61(void);
void InitTexture62(void);
void InitTexture63(void);
void InitTexture64(void);
void InitTexture65(void);
void InitTexture66(void);
void InitTexture67(void);
void InitTexture68(void);
void InitTexture69(void);


#endif
